### ISSUE TITLE
Request for additional stats

### ISSUE THREAD

**Issue by oliveratgithub** [qualiabyte/code-stats#4]
Hey there,
cool script, thanks a lot!

Would it be possible to add some additional stats for each file type discovered?

1. `Number of files`
2. `Summarised filesize`
3. `Average filesize` (= no. of files / sum filesize)
4. `Average line count` per file (= no. of files / line count)

And in the total row ofcourse summarize such.

That'd be great :)
Oliver

**Comment by qualiabyte** [comment]
@oliveratgithub Hi there, glad you found some usefulness in this tool!  While I'm not currently adding many new features to this tool personally, I am open to pull requests.  If they keep the code simple while maintaining a minimalist style of interface and output, that's definitely preferred!

Along these lines I've just recently merged the changes by @aaronbeall which add support for file counts and percentage statistics, and added better Windows support in the latest release version `0.3.1`.

**Comment by oliveratgithub** [comment]
Cool thanks!
